/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Package2;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Desk
 */
public class Login_Signup extends javax.swing.JFrame {

    /**
     * Creates new form Learning_app
     */
    public Login_Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        LoginMessageLabel = new javax.swing.JLabel();
        loginExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        ContactNo = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Password1 = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        ContactNoField = new javax.swing.JTextField();
        Username1Field = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        Password1Field = new javax.swing.JTextField();
        DOBField = new datechooser.beans.DateChooserCombo();
        SignupButton = new javax.swing.JButton();
        LoginPageButton = new javax.swing.JButton();
        loginExitButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LearningApp");
        setBounds(new java.awt.Rectangle(450, 180, 0, 0));
        setMaximumSize(new java.awt.Dimension(590, 380));
        setMinimumSize(new java.awt.Dimension(590, 380));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jPanel2.setLayout(null);

        Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        jPanel2.add(Username);
        Username.setBounds(143, 110, 96, 40);

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        jPanel2.add(Password);
        Password.setBounds(147, 180, 92, 36);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(PasswordField);
        PasswordField.setBounds(270, 188, 190, 30);

        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UsernameField);
        UsernameField.setBounds(270, 118, 190, 30);

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel6.setText("Login");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(258, 0, 100, 30);

        LoginButton.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton);
        LoginButton.setBounds(241, 271, 110, 30);

        SignUpButton.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        SignUpButton.setText("SignUp");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SignUpButton);
        SignUpButton.setBounds(241, 329, 110, 30);

        LoginMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(LoginMessageLabel);
        LoginMessageLabel.setBounds(60, 70, 513, 36);

        loginExitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginExitButton.setText("X");
        loginExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginExitButton);
        loginExitButton.setBounds(550, 0, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Desert.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-6, 4, 600, 390);

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("Signup");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(283, 0, 128, 44);

        FirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FirstName.setText("First Name");
        jPanel3.add(FirstName);
        FirstName.setBounds(28, 88, 80, 30);

        LastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LastName.setText("Last Name");
        jPanel3.add(LastName);
        LastName.setBounds(330, 100, 94, 15);

        Username1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Username1.setText("Username");
        jPanel3.add(Username1);
        Username1.setBounds(28, 264, 76, 30);

        ContactNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ContactNo.setText("Contact No.");
        jPanel3.add(ContactNo);
        ContactNo.setBounds(28, 175, 86, 30);

        DOB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DOB.setText("DOB");
        jPanel3.add(DOB);
        DOB.setBounds(330, 170, 94, 22);

        Password1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Password1.setText("Password");
        jPanel3.add(Password1);
        Password1.setBounds(320, 260, 94, 30);
        jPanel3.add(FirstNameField);
        FirstNameField.setBounds(110, 90, 145, 28);
        jPanel3.add(ContactNoField);
        ContactNoField.setBounds(110, 180, 147, 30);
        jPanel3.add(Username1Field);
        Username1Field.setBounds(110, 270, 147, 30);
        jPanel3.add(LastNameField);
        LastNameField.setBounds(410, 90, 170, 30);
        jPanel3.add(Password1Field);
        Password1Field.setBounds(410, 260, 170, 30);
        jPanel3.add(DOBField);
        DOBField.setBounds(410, 170, 155, 30);

        SignupButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SignupButton.setText("SignUp");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SignupButton);
        SignupButton.setBounds(320, 320, 141, 31);

        LoginPageButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginPageButton.setText("Login Page");
        LoginPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPageButtonActionPerformed(evt);
            }
        });
        jPanel3.add(LoginPageButton);
        LoginPageButton.setBounds(140, 320, 141, 30);

        loginExitButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginExitButton1.setText("X");
        loginExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(loginExitButton1);
        loginExitButton1.setBounds(550, 0, 40, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images.jpeg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(-6, -6, 600, 390);

        jTabbedPane1.addTab("tab2", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 640, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
              // TODO add your handling code here:
          String Username=Username1Field.getText();
        String Password=Password1Field.getText();  
        String FirstName=FirstNameField.getText(); 
        String LastName=LastNameField.getText(); 
        
        String MobileNo=ContactNoField.getText();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("Driver Loaded");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/learning_app", "root", "Bhaisachin12@");
        System.out.println("Connection Established");
         PreparedStatement Check=con.prepareStatement("select Username from Login where username='"+Username+"'");
        ResultSet rs=Check.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(this,"!!Name Already Taken!!");
            
        }
        else{
        PreparedStatement Create=con.prepareStatement("Insert into login (FirstName,LastName,Mobile,DOB,Username,Password) values ('"+FirstName+"','"+LastName+"','"+MobileNo+"','"+DOB.getText()+"','"+Username+"','"+Password+"')");
        Create.executeUpdate();
        System.out.println("value inserted");
        JOptionPane.showMessageDialog(this,"Sign in Successfully");
        }
                }catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void LoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPageButtonActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_LoginPageButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String Username=UsernameField.getText();
        String Password=PasswordField.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/learning_app", "root", "Bhaisachin12@");
            System.out.println("Connection Established");
            PreparedStatement Create=con.prepareStatement("select Username,Password from Login where Username='"+Username+"'and Password='"+Password+"'");
            ResultSet rs=Create.executeQuery();
            if(rs.next())
            {
                System.out.println("found loggin");
               
                Learning_app la=new Learning_app();
                la.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                LoginMessageLabel.setText("Incorrect Username or Password");
                LoginMessageLabel.setVisible(true);
            }
        }catch(SQLException e)
        {
            System.out.println("SQL exception"+e.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println("class not found exception"+ex.getMessage());
        }             // TODO add your handling code here:

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
      jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void loginExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_loginExitButtonActionPerformed

    private void loginExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_loginExitButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNo;
    private javax.swing.JTextField ContactNoField;
    private javax.swing.JLabel DOB;
    private datechooser.beans.DateChooserCombo DOBField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginMessageLabel;
    private javax.swing.JButton LoginPageButton;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JTextField Password1Field;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JTextField Username1Field;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginExitButton;
    private javax.swing.JButton loginExitButton1;
    // End of variables declaration//GEN-END:variables
}
