/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Package2;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Desk
 */
public class Login_Signup extends javax.swing.JFrame {

    /**
     * Creates new form Learning_app
     */
    public Login_Signup() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LoginPage = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        LoginMessageLabel = new javax.swing.JLabel();
        loginExitButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        SignUpPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        ContactNo = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Password1 = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        ContactNoField = new javax.swing.JTextField();
        Username1Field = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        Password1Field = new javax.swing.JTextField();
        DOBField = new datechooser.beans.DateChooserCombo();
        SignupButton = new javax.swing.JButton();
        LoginPageButton = new javax.swing.JButton();
        loginExitButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LearningApp");
        setBounds(new java.awt.Rectangle(450, 180, 0, 0));
        setMinimumSize(new java.awt.Dimension(590, 380));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        LoginPage.setLayout(null);

        Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        LoginPage.add(Username);
        Username.setBounds(143, 110, 96, 40);

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        LoginPage.add(Password);
        Password.setBounds(147, 180, 92, 36);

        UsernameField.setBackground(new java.awt.Color(237, 237, 237));
        UsernameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(153, 153, 153));
        UsernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameField.setText("Enter Username");
        UsernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameFieldMouseClicked(evt);
            }
        });
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        LoginPage.add(UsernameField);
        UsernameField.setBounds(270, 118, 190, 30);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");
        LoginPage.add(jLabel6);
        jLabel6.setBounds(270, 0, 100, 30);

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginButton.setBorderPainted(false);
        LoginButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LoginButtonMouseMoved(evt);
            }
        });
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginButtonMouseReleased(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPage.add(LoginButton);
        LoginButton.setBounds(40, 280, 530, 30);

        SignUpButton.setBackground(new java.awt.Color(255, 255, 255));
        SignUpButton.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SignUpButton.setText("SignUp");
        SignUpButton.setBorderPainted(false);
        SignUpButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseMoved(evt);
            }
        });
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseExited(evt);
            }
        });
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        LoginPage.add(SignUpButton);
        SignUpButton.setBounds(260, 330, 110, 30);

        LoginMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
        LoginPage.add(LoginMessageLabel);
        LoginMessageLabel.setBounds(50, 70, 513, 36);

        loginExitButton.setBackground(new java.awt.Color(255, 132, 132));
        loginExitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginExitButton.setForeground(new java.awt.Color(255, 255, 255));
        loginExitButton.setText("X");
        loginExitButton.setBorderPainted(false);
        loginExitButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginExitButtonMouseMoved(evt);
            }
        });
        loginExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginExitButtonMouseExited(evt);
            }
        });
        loginExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButtonActionPerformed(evt);
            }
        });
        LoginPage.add(loginExitButton);
        loginExitButton.setBounds(550, 0, 40, 20);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        LoginPage.add(PasswordField);
        PasswordField.setBounds(270, 190, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Screenshot_2.png"))); // NOI18N
        LoginPage.add(jLabel1);
        jLabel1.setBounds(-10, 0, 620, 380);

        jTabbedPane1.addTab("tab1", LoginPage);

        SignUpPage.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Signup");
        SignUpPage.add(jLabel2);
        jLabel2.setBounds(283, 0, 128, 44);

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");
        SignUpPage.add(FirstName);
        FirstName.setBounds(28, 88, 80, 30);

        LastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");
        SignUpPage.add(LastName);
        LastName.setBounds(330, 100, 94, 15);

        Username1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Username1.setForeground(new java.awt.Color(255, 255, 255));
        Username1.setText("Username");
        SignUpPage.add(Username1);
        Username1.setBounds(28, 264, 76, 30);

        ContactNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ContactNo.setForeground(new java.awt.Color(255, 255, 255));
        ContactNo.setText("Contact No.");
        SignUpPage.add(ContactNo);
        ContactNo.setBounds(28, 175, 86, 30);

        DOB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("DOB");
        SignUpPage.add(DOB);
        DOB.setBounds(330, 170, 60, 22);

        Password1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Password1.setForeground(new java.awt.Color(255, 255, 255));
        Password1.setText("Password");
        SignUpPage.add(Password1);
        Password1.setBounds(320, 260, 94, 30);

        FirstNameField.setBackground(new java.awt.Color(229, 229, 229));
        FirstNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameFieldMouseClicked(evt);
            }
        });
        SignUpPage.add(FirstNameField);
        FirstNameField.setBounds(110, 90, 145, 28);

        ContactNoField.setBackground(new java.awt.Color(229, 229, 229));
        ContactNoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactNoFieldMouseClicked(evt);
            }
        });
        SignUpPage.add(ContactNoField);
        ContactNoField.setBounds(110, 180, 147, 30);

        Username1Field.setBackground(new java.awt.Color(229, 229, 229));
        Username1Field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Username1FieldMouseClicked(evt);
            }
        });
        SignUpPage.add(Username1Field);
        Username1Field.setBounds(110, 270, 147, 30);

        LastNameField.setBackground(new java.awt.Color(229, 229, 229));
        LastNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastNameFieldMouseClicked(evt);
            }
        });
        SignUpPage.add(LastNameField);
        LastNameField.setBounds(410, 90, 170, 30);

        Password1Field.setBackground(new java.awt.Color(229, 229, 229));
        Password1Field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Password1FieldMouseClicked(evt);
            }
        });
        SignUpPage.add(Password1Field);
        Password1Field.setBounds(410, 260, 170, 30);

        DOBField.setCalendarBackground(new java.awt.Color(224, 224, 224));
        DOBField.addCursorMoveListener(new datechooser.events.CursorMoveListener() {
            public void onCursorMove(datechooser.events.CursorMoveEvent evt) {
                DOBFieldOnCursorMove(evt);
            }
        });
        SignUpPage.add(DOBField);
        DOBField.setBounds(410, 170, 155, 30);

        SignupButton.setBackground(new java.awt.Color(255, 255, 255));
        SignupButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SignupButton.setText("SignUp");
        SignupButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SignupButtonMouseMoved(evt);
            }
        });
        SignupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupButtonMouseExited(evt);
            }
        });
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        SignUpPage.add(SignupButton);
        SignupButton.setBounds(280, 320, 90, 30);

        LoginPageButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginPageButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginPageButton.setText("Login Page");
        LoginPageButton.setContentAreaFilled(false);
        LoginPageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LoginPageButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LoginPageButtonMouseMoved(evt);
            }
        });
        LoginPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPageButtonMouseExited(evt);
            }
        });
        LoginPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPageButtonActionPerformed(evt);
            }
        });
        SignUpPage.add(LoginPageButton);
        LoginPageButton.setBounds(290, 360, 100, 20);

        loginExitButton1.setBackground(new java.awt.Color(255, 132, 132));
        loginExitButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginExitButton1.setText("X");
        loginExitButton1.setContentAreaFilled(false);
        loginExitButton1.setOpaque(true);
        loginExitButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginExitButton1MouseMoved(evt);
            }
        });
        loginExitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginExitButton1MouseExited(evt);
            }
        });
        loginExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButton1ActionPerformed(evt);
            }
        });
        SignUpPage.add(loginExitButton1);
        loginExitButton1.setBounds(550, 0, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("or back to ");
        SignUpPage.add(jLabel4);
        jLabel4.setBounds(240, 360, 60, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Screenshot_2.png"))); // NOI18N
        SignUpPage.add(jLabel3);
        jLabel3.setBounds(0, -10, 600, 390);

        jTabbedPane1.addTab("tab2", SignUpPage);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 640, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
              // TODO add your handling code here:
        String Username=Username1Field.getText();
        String Password=Password1Field.getText();  
        String FirstName=FirstNameField.getText(); 
        String LastName=LastNameField.getText(); 
        String MobileNo=ContactNoField.getText();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("Driver Loaded");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/learning_app", "root", "Bhaisachin12@");
        System.out.println("Connection Established");
         PreparedStatement Check=con.prepareStatement("select Username from Login where username='"+Username+"'");
        ResultSet rs=Check.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(this,"!!Name Already Taken!!");
        }
        else{
        PreparedStatement Create=con.prepareStatement("Insert into login (FirstName,LastName,Mobile,DOB,Username,Password) values ('"+FirstName+"','"+LastName+"','"+MobileNo+"','"+DOB.getText()+"','"+Username+"','"+Password+"')");
        Create.executeUpdate();
        System.out.println("value inserted");
        JOptionPane.showMessageDialog(this,"Sign in Successfully");
        JOptionPane.showMessageDialog(this,"Sign in Successfully");
        }
                }catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void LoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPageButtonActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_LoginPageButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        Loading lp=new Loading();            
        String Username=UsernameField.getText();
        String Password=PasswordField.getText();
        try{
            PreparedStatement Create=this.connection().prepareStatement("select Username,Password from Login where Username='"+Username+"'and Password='"+Password+"'");
            ResultSet rs=Create.executeQuery();
            if(rs.next())
            {      
                   System.out.println("found Login");
                   Learning_app la=new Learning_app();
                   this.setVisible(false);
                   la.setVisible(true);
            }
            else
            {
                LoginMessageLabel.setText("Incorrect Username or Password");
                LoginMessageLabel.setVisible(true); 
            }
        }catch(SQLException e)
        {
            System.out.println("SQL exception"+e.getMessage());
        }        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
      jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void loginExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_loginExitButtonActionPerformed

    private void loginExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_loginExitButton1ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void UsernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameFieldMouseClicked
     UsernameField.setBackground(Color.WHITE);        // TODO add your handling code here:
     UsernameField.setForeground(Color.BLACK);        // TODO add your handling code here:
     UsernameField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
          
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void LoginButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseReleased

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
LoginButton.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseExited

    private void loginExitButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginExitButtonMouseMoved
         loginExitButton.setBackground(new java.awt.Color(255, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_loginExitButtonMouseMoved

    private void loginExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginExitButtonMouseExited
      loginExitButton.setBackground(new java.awt.Color(255, 132, 132));
        // TODO add your handling code here:
    }//GEN-LAST:event_loginExitButtonMouseExited

    private void LoginButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseMoved
          LoginButton.setBackground(Color.cyan);// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseMoved

    private void SignUpButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseMoved
        SignUpButton.setBackground(Color.cyan);
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonMouseMoved

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseExited
                   SignUpButton.setBackground(Color.white);
    // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonMouseExited

    private void loginExitButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginExitButton1MouseMoved
      loginExitButton1.setBackground(new java.awt.Color(255, 0, 0));  // TODO add your handling code here:
    }//GEN-LAST:event_loginExitButton1MouseMoved

    private void loginExitButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginExitButton1MouseExited
               loginExitButton1.setBackground(new java.awt.Color(255, 132, 132));  // TODO add your handling code here:
  // TODO add your handling code here:
    }//GEN-LAST:event_loginExitButton1MouseExited

    private void FirstNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameFieldMouseClicked
       FirstNameField.setBackground(new java.awt.Color(255, 255, 255)); // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldMouseClicked

    private void LastNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastNameFieldMouseClicked
       LastNameField.setBackground(new java.awt.Color(255, 255, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFieldMouseClicked

    private void ContactNoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactNoFieldMouseClicked
       ContactNoField.setBackground(new java.awt.Color(255, 255, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNoFieldMouseClicked

    private void Username1FieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username1FieldMouseClicked
        Username1Field.setBackground(new java.awt.Color(255, 255, 255));      // TODO add your handling code here:
    }//GEN-LAST:event_Username1FieldMouseClicked

    private void Password1FieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password1FieldMouseClicked
        Password1Field.setBackground(new java.awt.Color(255, 255, 255));        
    }//GEN-LAST:event_Password1FieldMouseClicked

    private void DOBFieldOnCursorMove(datechooser.events.CursorMoveEvent evt) {//GEN-FIRST:event_DOBFieldOnCursorMove
        DOBField.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_DOBFieldOnCursorMove

    private void LoginPageButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPageButtonMouseMoved
         LoginPageButton.setForeground(Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPageButtonMouseMoved

    private void LoginPageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPageButtonMouseExited
         LoginPageButton.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPageButtonMouseExited

    private void SignupButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseMoved
         SignupButton.setBackground(Color.cyan);        // TODO add your handling code here:
    }//GEN-LAST:event_SignupButtonMouseMoved

    private void SignupButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseExited
          SignupButton.setBackground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_SignupButtonMouseExited
    public Connection connection()
    {
        
        Connection con=null;
        try{
             Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/learning_app", "root", "Bhaisachin12@");
            System.out.println("Connection Established");
          } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login_Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        return con;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNo;
    private javax.swing.JTextField ContactNoField;
    private javax.swing.JLabel DOB;
    private datechooser.beans.DateChooserCombo DOBField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginMessageLabel;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JButton LoginPageButton;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JTextField Password1Field;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel SignUpPage;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JTextField Username1Field;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginExitButton;
    private javax.swing.JButton loginExitButton1;
    // End of variables declaration//GEN-END:variables
}
